### PR TITLE
Website/benchmarks: add FTPP benchmark

### PR DESCRIPTION
**Pull request by ennoruijters**
Hi Arnd,

This is one of the fault trees we talked about adding to the benchmark set. Let me know if I've gotten all the JSON correct.

### CODE REVIEW

**Comment by ennoruijters** [comment]
Okay, I've amended my commit to have all the files in lower case.

**Comment by ahartmanns** [comment]
Great, thanks!
And sorry that I didn't look in detail before, here's a few more small requests:
- Since all model parameters are of "kind": "file", the values specified for those parameters for the files should be "file-parameter-values", not "open-parameter-values". (See mdp/beb for an example.) Though keep the latter (but empty) so we can add state space sizes later.
- Could you shorten the "challenge" to "rare event, small weak bisimulation quotient", and add a sentence (that also mentions that the quotient is a CTMC, i.e. no more nondeterminism) about this to the description?

**Comment by ennoruijters** [comment]
I've made the changes you requested.

**Comment by ennoruijters** [comment]
Hi Arnd,

I've rebased onto your current master.

**Comment by ahartmanns** [comment]
Merged in 42bac7624f16b7f9f8e80f82bdbb261f67b1c9f2.

**Pull request closed without merging**
